### PR TITLE
Add instance of RDS

### PR DESCRIPTION
**Pull request by chenyingkof**
This PR is used for rds instance resource of otc terraform provider.

### CODE REVIEW

**Comment by gator1** [comment]
I request all the pull requests go to integration branch, this way I could do a final test before merging to the master

**Comment by gator1** [comment]
You need to provide a full acceptance test. Without it a pull request can't be accepted.

**Comment by chenyingkof** [comment]
OK. I will add acceptance test about it.

**Comment by chenyingkof** [comment]
@gator1  hi gary, the acceptance tests about Rds instance have been added. 
This link shows the result log about passed the acceptance tests[1].

[1] http://paste.openstack.org/show/638105/

**Pull request merged**
