### PR TITLE
enable support for vpc service

### PR DESCRIPTION
**Pull request by Savasw**

### CODE REVIEW

**Comment by gator1** [comment]
@Savasw I am in the process of trying to separate the original gophercloud and huawei specific. 
Right now we are changing gophercloud, this makes it difficult to sync up with the future development of upstream gophercloud. I am trying to first not to change my version of gophercloud basic data structure, only add functions or data structure. Other team tried to change provider_client.go and added a ProjectID there. That caused problems for my separation effort. I am not sure if you need ProjectID or just sync up with the older code. Please review and change it.

**Comment by gator1** [comment]
ProjectID was added in the basic structure and later removed. It looks like you are using the older code.

**Comment by Savasw** [comment]
I can reuse other team's functions (zengchen1024)  which they have created to avoid changes in existing methods and data structure to get project id. Are you good with this approach?

**Comment by gator1** [comment]
Yes I am good with that.

**Comment by Savasw** [comment]
@gator1 , i have reverted changes related to core structure. If this is good with you, i will vendor latest gophercloud for terraform.

**Pull request merged**
